//
// Test Bench Module my_project_lib.flow_control_tb.flow_control_tester
//
// Created:
//          by - Eugene.UNKNOWN (DESKTOP-BCGV2R3)
//          at - 21:27:49 05-Feb-24
//
// Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
//
`resetall
`timescale 1ns/10ps

module flow_control_tb;

// Local declarations
parameter BUS_WIDTH = 32;
parameter DATA_WIDTH = 8;

// Internal signal declarations
wire [(BUS_WIDTH / DATA_WIDTH) * BUS_WIDTH - 1:0] a_row_i;
wire [(BUS_WIDTH / DATA_WIDTH) * BUS_WIDTH - 1:0] b_col_i;
wire                                              clk_i;
wire                                              rst_ni;
wire                                              start_bit;
wire [(BUS_WIDTH / DATA_WIDTH) * BUS_WIDTH - 1:0] a_row_o;
wire [(BUS_WIDTH / DATA_WIDTH) * BUS_WIDTH - 1:0] b_col_o;

flow_control #(BUS_WIDTH,DATA_WIDTH) U_0(
   .a_row_i   (a_row_i),
   .b_col_i   (b_col_i),
   .clk_i     (clk_i),
   .rst_ni     (rst_ni),
   .start_bit (start_bit),
   .a_row_o   (a_row_o),
   .b_col_o   (b_col_o)
);

flow_control_tester #(BUS_WIDTH,DATA_WIDTH) U_1(
   .a_row_i   (a_row_i),
   .b_col_i   (b_col_i),
   .clk_i     (clk_i),
   .rst_ni     (rst_ni),
   .start_bit (start_bit),
   .a_row_o   (a_row_o),
   .b_col_o   (b_col_o)
);

endmodule // flow_control_tb


