//
// Test Bench Module my_project_lib.HALF_MUL_tb.HALF_MUL_tester
//
// Created:
//          by - Eugene.UNKNOWN (DESKTOP-BCGV2R3)
//          at - 23:06:20 06-Feb-24
//
// Generated by Mentor Graphics' HDL Designer(TM) 2021.1 Built on 14 Jan 2021 at 15:11:42
//
`resetall
`timescale 1ns/10ps

module HALF_MUL_tb;

// Local declarations
parameter BUS_WIDTH = 32;
parameter DATA_WIDTH = 8;
parameter DIM = BUS_WIDTH/DATA_WIDTH;
// Internal signal declarations
wire [DIM * BUS_WIDTH - 1:0]                                   a_row_i;
wire [DIM * BUS_WIDTH - 1:0]                                   b_col_i;
wire                                                           clk_i;
wire                                                           rst_ni;
wire                                                           start_bit;
wire                                                           busy;
wire                                                           done_o;
wire [DIM * DIM - 1:0] ouflow_o;
wire [DIM * DIM * BUS_WIDTH - 1:0]                             fin_r_o;


HALF_MUL #(BUS_WIDTH,DATA_WIDTH) U_0(
   .a_row_i   (a_row_i),
   .b_col_i   (b_col_i),
   .clk_i     (clk_i),
   .rst_ni     (rst_ni),
   .start_bit (start_bit),
   .busy      (busy),
   .done_o    (done_o),
   .ouflow_o  (ouflow_o),
   .fin_r_o   (fin_r_o)
);

HALF_MUL_tester #(BUS_WIDTH,DATA_WIDTH) U_1(
   .a_row_i   (a_row_i),
   .b_col_i   (b_col_i),
   .clk_i     (clk_i),
   .rst_ni     (rst_ni),
   .start_bit (start_bit),
   .busy      (busy),
   .done_o    (done_o),
   .ouflow_o  (ouflow_o),
   .fin_r_o   (fin_r_o)
);

endmodule // HALF_MUL_tb


